### ISSUE TITLE
[FEATURE] 컴포넌트 설계

### ISSUE THREAD

**Issue by 9yujin** [bankidz/bankidz-client#22]
# 🤖 기능 개요
재활용이 가능한 컴포넌트 단위로 우선 설계합니다.

### ✅ Implement TODO

- [ ] 온보딩
- [ ] 뱃지
- [x] 네비게이션
- [ ] 자녀 홈
- [ ] 부모 홈
- [ ] 돈길 모아보기
- [ ] 마이페이지

### 📚 Remarks
[https://bankidz.github.io/bankidz-client/](https://bankidz.github.io/bankidz-client/)

**Comment by 24siefil** [comment]
불필요한 이슈로 판단하여 Close 하겠습니다. 필요한 경우 말씀해주세요!
